<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12</LangVersion>

    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <IncludeAssets>
        runtime; build; native; contentfiles; analyzers; buildtransitive
      </IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Compile
      Include="..\..\Data\Scripts\CommandAPI\ModVersionFile.cs"
      Link="ModVersionFile.cs" />
    <Compile
      Include="..\..\Data\Scripts\CommandAPI\ApiVersionFile.cs"
      Link="ApiVersionFile.cs" />
    <Compile
      Include="..\..\Data\Scripts\CommandAPI\Core\**\*.cs"
      Link="Core\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile
      Include="..\..\Data\Scripts\CommandAPI\Api\**\*.cs"
      Link="Api\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile
      Include="..\..\Data\Scripts\CommandAPI\Libraries\Mz.ApiProtocol.Core\**\*.cs"
      Link="Libraries\Mz.ApiProtocol.Core\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile
      Include="..\..\Data\Scripts\CommandAPI\Libraries\Mz.ApiProtocol.SpaceEngineers\**\*.cs"
      Exclude="..\..\Data\Scripts\CommandAPI\Libraries\Mz.ApiProtocol.SpaceEngineers\Messaging\SpaceEngineersModMessageBus.cs"
      Link="Libraries\Mz.ApiProtocol.SpaceEngineers\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile
      Include="..\..\Data\Scripts\CommandAPI\Libraries\Mz.SemanticVersioning\**\*.cs"
      Link="Libraries\Mz.SemanticVersioning\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>

  <ItemGroup>
    <Compile
      Include="..\..\Data\Scripts\CommandAPI\Chat\RichHudChatCommandAdapter.cs"
      Link="Chat\RichHudChatCommandAdapter.cs" />
    <Compile
      Include="..\..\Data\Scripts\CommandAPI\Chat\VanillaChatCommandSubmitter.cs"
      Link="Chat\VanillaChatCommandSubmitter.cs" />
  </ItemGroup>

</Project>